sudo: required

services:
  - docker


before_install:
  - docker build -t ralucab/docker-react -f Dockerfile.dev .

script:
  - docker run ralucab/docker-react npm run test -- --coverage

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "myweb"
  env: "Myweb-env"
  bucket_name: elasticbeanstalk-us-east-2-243348670467
  bucket_path: "myweb" 
  on:
    branch: master
  access_key_id: 
    secure: "AWS_ACCESS_KEY1"
  secret_access_key: 
    secure: "$AWS_SECRET_KEY1"